#    This file is part of darktable,
#    Copyright (C) 2016-2017, 2019 Roman Lebedev.
#    Copyright (C) 2020 Hubert Kowalski.
#    Copyright (C) 2021 parafin.
#    Copyright (C) 2022 Apfelkraut.
#    Copyright (C) 2022-2023, 2025 Aurélien PIERRE.
#    Copyright (C) 2024 jakehl.
#    Copyright (C) 2025 Miguel Moquillon.
#    
#    darktable is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#    
#    darktable is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#    
#    You should have received a copy of the GNU General Public License
#    along with darktable.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
#
#
#
#
#
#
#    
brew 'cmake'
brew 'pkg-config'
brew 'curl'
brew 'desktop-file-utils'
brew 'exiv2'
brew 'gettext'
brew 'git'
brew 'glib'
brew 'gtk+3'
brew 'gtk-mac-integration'
brew 'icu4c'
brew 'intltool'
brew 'iso-codes'
brew 'jpeg-turbo'
brew 'jpeg-xl'
brew 'json-glib'
brew 'lensfun'
brew 'libavif'
brew 'libheif'
brew 'libomp'
brew 'libraw'
brew 'librsvg'
brew 'little-cms2'
brew 'ninja'
brew 'openexr'
brew 'openjpeg'
brew 'osm-gps-map'
brew 'perl'
brew 'po4a'
brew 'pugixml'
brew 'sdl2'
brew 'webp'
brew 'cmocka'
