#-------------------------------------------------------------------------------
# ansel_write_module_manifest(<install-dir> <target>...)
#
# Write, and install into <install-dir>, the manifest that tells Ansel which
# modules it may dlopen from that directory.
#
# The application used to scan the directory and load every shared object it found.
# That trusts the filesystem to be exactly what the installer left, and it is not:
# a failed or partial upgrade leaves modules from an older build behind, and the only
# gate between them and the process is DT_MODULE_VERSION -- a hand-bumped constant
# that does not move when a struct grows a member. Such a module loads happily and
# then reads a layout that no longer exists.
#
# The build knows exactly which modules it produced. Writing that list down beside
# them, and loading nothing else, is the whole fix -- and it costs one file per
# directory on every platform, not just the one where the problem was noticed.
#
# The names are TARGET_FILE_BASE_NAME, not the CMake target names: they must be what
# g_module_build_path() expects, and at least one target (avif_format) is installed
# under a different OUTPUT_NAME than the target that builds it.
#-------------------------------------------------------------------------------
function(ansel_write_module_manifest install_dir)
  set(targets ${ARGN})

  set(header "# Ansel module manifest -- generated by cmake, do not edit.\n")
  string(APPEND header "# Ansel loads these modules from this directory, and nothing else.\n")
  string(APPEND header "# One module base name per line; '#' starts a comment.\n")

  set(body "")
  foreach(target ${targets})
    string(APPEND body "$<TARGET_FILE_BASE_NAME:${target}>\n")
  endforeach()

  set(manifest "${CMAKE_CURRENT_BINARY_DIR}/modules.manifest")
  file(GENERATE OUTPUT "${manifest}" CONTENT "${header}${body}")

  install(FILES "${manifest}" DESTINATION "${install_dir}" COMPONENT DTApplication)
endfunction()
