#   This file is part of the Ansel project.
#   Copyright (C) 2022-2026 Aurélien PIERRE.
#   Copyright (C) 2023-2024 Alynx Zhou.
#   Copyright (C) 2025 Guillaume Stutin.
#   
#   Ansel is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   Ansel is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with Ansel.  If not, see <http://www.gnu.org/licenses/>.










name: Nightly Linux PKG

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  Linux:
    if: github.repository == 'aurelienpierreeng/ansel' || github.event_name == 'workflow_dispatch'
    name: Nightly Ansel Linux build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        btype:
          - RelWithDebInfo
        compiler:
          - { compiler: GNU12, CC: gcc-12, CXX: g++-12, GCC_VER: "12", LLVM_VER: "" }
        eco: [-DBINARY_PACKAGE_BUILD=ON -DUSE_XMLLINT=OFF]
        target:
          - skiptest
        generator:
          - Ninja
        branch:
          - { code: "${{ github.ref_name }}", label: stable }
    env:
      CC: ${{ matrix.compiler.CC }}
      CXX: ${{ matrix.compiler.CXX }}
      GCC_VER: ${{ matrix.compiler.GCC_VER }}
      LLVM_VER: ${{ matrix.compiler.LLVM_VER }}
      SRC_DIR: ${{ github.workspace }}/src
      BUILD_DIR: ${{ github.workspace }}/build
      INSTALL_PREFIX: ${{ github.workspace }}/AppDir/usr
      ECO: ${{ matrix.eco }}
      CMAKE_BUILD_TYPE: ${{ matrix.btype }}
      GENERATOR: ${{ matrix.generator }}
      TARGET: ${{ matrix.target }}
      DARKTABLE_CLI: ${{ github.workspace }}/AppDir/usr/bin/ansel-cli
      BRANCH: ${{ matrix.branch.code }}
      BUILD_NAME: ${{ matrix.branch.label }}
    steps:
      - name: Enable Ubuntu repositories
        run: |
          sudo add-apt-repository -y universe
          sudo add-apt-repository -y multiverse
          sudo apt-get update
          sudo apt-get upgrade
      - name: Checkout ansel source
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH }}
          fetch-depth: 5000
          fetch-tags: true
          submodules: true
          path: src
      - name: Install Base Dependencies
        env: 
          JXL_ALLOW_NOBLE: 1
        run: |
          "${SRC_DIR}/packaging/install-deps-ubuntu.sh"
      - name: Update lensfun data for root
        if: ${{ success() }}
        run: |
          sudo lensfun-update-data
      - name: Build and Install
        run: |
          cd src
          bash .ci/ci-script-appimage.sh
      - name: Package upload
        if: ${{ success() }}
        uses: actions/upload-artifact@v6
        with:
          name: ansel.${{ env.BUILD_NAME }}.AppImage
          path: ${{ env.SRC_DIR }}/build/Ansel-*-x86_64.AppImage*
          retention-days: 90

  upload_to_release:
    runs-on: ubuntu-latest
    env:
      REPO: "https://github.com/aurelienpierreeng/ansel"
      ROOM: "!SgRYbzspwqwwUgSQHC:matrix.org"
      TAG: "v0.0.0"
    needs: Linux
    steps:
      - name: Checkout ansel source
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: false

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ansel.stable.AppImage
      - name: Update nightly release
        uses: aurelienpierreeng/tip@master
        with:
          tag: ${{ env.TAG }}
          rm: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: Ansel-*.AppImage*

      - name: Install dependencies
        run: |
          python -m pip install simplematrixbotlib

      - name: Notify Matrix
        if: ${{ success() }}
        run: |
          FILENAME=$(tr '~' '.' <<< "$(find . -type f -iname "Ansel-*.AppImage")")
          MESSAGE="New AppImage [${FILENAME}](${{ env.REPO }}/releases/download/${{ env.TAG }}/${FILENAME}) built"
          python .ci/matrix.py \
          -m "$MESSAGE" \
          -s ${{ secrets.MATRIX_SERVER }} \
          -u ${{ secrets.MATRIX_USER }} \
          -t ${{ secrets.MATRIX_ACCESS }} \
          -r ${{ env.ROOM }}
