#   This file is part of the Ansel project.
#   Copyright (C) 2023 Aurélien PIERRE.
#   
#   Ansel is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#   
#   Ansel is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with Ansel.  If not, see <http://www.gnu.org/licenses/>.










name: Matrix bot

on:
  push:
    branches:
      - master
  pull_request_target:
    types: [opened, edited, reopened, closed]
  issues:
    types: [opened, edited, milestoned, closed]

jobs:
  matrix_action_job:
    runs-on: ubuntu-latest
    name: Send Message to Matrix Room
    env:
      REPO: "https://github.com/aurelienpierreeng/ansel"
      ROOM: "!khBjOtEnQNuCYlWScJ:matrix.org"
    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        python -m pip install simplematrixbotlib

    - name: Dispatch message - new commit
      if: github.event_name == 'push'
      run: |
        GIT_HASH=$(git rev-parse HEAD)
        MESSAGE="Commit [$(git rev-parse --short HEAD)](${{ env.REPO }}/commit/${GIT_HASH}): $(git show -s --format=%s)"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - new issue
      if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
      env:
        TITLE: ${{ github.event.issue.title }}
      run: |
        MESSAGE="New issue [${{ github.event.issue.number }}](${{ github.event.issue.html_url }}) (_${TITLE}_) created"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - issue edited
      if: ${{ github.event_name == 'issues' && github.event.action == 'edited' }}
      env:
        TITLE: ${{ github.event.issue.title }}
      run: |
        MESSAGE="Issue [${{ github.event.issue.number }}](${{ github.event.issue.html_url }}) (_${TITLE}_) edited"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - issue milestoned
      if: ${{ github.event_name == 'issues' && github.event.action == 'milestoned' }}
      env:
        TITLE: ${{ github.event.issue.title }}
        MILESTONE: ${{ github.event.issue.milestone.title }}
      run: |
        MESSAGE="Issue [${{ github.event.issue.number }}](${{ github.event.issue.html_url }}) (_${TITLE}_) milestoned for ${MILESTONE}"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - issue closed
      if: ${{ github.event_name == 'issues' && github.event.action == 'closed' }}
      env:
        TITLE: ${{ github.event.issue.title }}
      run: |
        MESSAGE="Issue [${{ github.event.issue.number }}](${{ github.event.issue.html_url }}) (_${TITLE}_) closed"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - new PR
      if: ${{ github.event_name == 'pull_request_target' && github.event.action == 'opened' }}
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: |
        MESSAGE="New PR [${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) (_${TITLE}_) created"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - PR edited
      if: ${{ github.event_name == 'pull_request_target' && github.event.action == 'edited' }}
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: |
        MESSAGE="PR [${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) (_${TITLE}_) edited"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}

    - name: Dispatch message - PR closed
      if: ${{ github.event_name == 'pull_request_target' && github.event.action == 'closed' }}
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: |
        MESSAGE="PR [${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) (_${TITLE}_) closed"
        python .ci/matrix.py \
        -m "$MESSAGE" \
        -s ${{ secrets.MATRIX_SERVER }} \
        -u ${{ secrets.MATRIX_USER }} \
        -t ${{ secrets.MATRIX_ACCESS }} \
        -r ${{ env.ROOM }}
